baseURL = 'https://nmimusic.github.io/'
languageCode = 'ja-jp'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = '中村音楽工業'
theme = 'universal'
copyright = '(C) 2023-2024 NAKAMURA MUSICAL INDUSTRIES'

[params]
	viewMorePostLink = ["/news/"]
	author = "NAKAMURA MUSICAL INDUSTRIES"
	defaultKeywords = ["中村音楽工業", "中村音工", "NMI", "同人音楽"]
	mainSections = ["news", "music", "games", "lgx", "creators", "support"]

	about_us = "<p>同人クラブ「一般社団同人中村音楽工業」の公式サイト。所属クリエイターのお知らせや新譜の発売情報、ゲーム、イベント出演情報、メディア情報などを掲載。</p>"
	copyright = "Copyright (C) 2023-2024 NAKAMURA MUSICAL INDUSTRIES (NMI) all rights reserved."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	dropdown_mouse_over = false

	disabled_logo = false
	logo_text = "NMI Music"

	logo = "/img/logo.png"
	logo_small = "/img/logo.png"

	pluralizelisttitles = false

[params.widgets]
	categories = true
	tags = true
	search = true

[params.carouselHomepage]
	enable = true
	auto_play = true
	slide_speed = 2000
	pagination_speed = 1000

[params.recent_news]
	enable = true
	title = "news"
	hide_summary = false

[params.recent_music]
	enable = true
	title = "music"
	hide_summary = false

[params.recent_games]
	enable = true
	title = "games"
	hide_summary = false

[params.recent_lgx]
	enable = true
	title = "linux/gnu/x distros"
	hide_summary = false

[params.recent_support]
	enable = true
	title = "support"
	hide_summary = false

[params.footer.recent_posts]
    enable = true

[menu]
[[menu.main]]
	name       = "ABOUT"
	url        = "/about/"
	weight     = 1

[[menu.main]]
	name       = "NEWS"
	url        = "/news/"
	weight     = 2

[[menu.main]]
	name       = "CREATORS"
	url        = "/creators/"
	weight     = 3

[[menu.main]]
	name       = "RELEASES"
	identifier = "menu.releases"
	url        = ""
	weight     = 4

[[menu.main]]
	name       = "Music"
	url        = "/music/"
	weight     = 1
	parent     = "menu.releases"

[[menu.main]]
	name       = "Games"
	url        = "/games/"
	weight     = 2
	parent     = "menu.releases"

[[menu.main]]
	name       = "Linux/GNU/X"
	url        = "/lgx/"
	weight     = 3
	parent     = "menu.releases"

[[menu.main]]
	name       = "SUPPORT"
	url        = ""
	identifier = "menu.support"
	weight     = 5

[[menu.main]]
	name       = "SUPPORT INFORMATIONS"
	url        = "/support/"
	weight     = 1
	parent     = "menu.support"

[[menu.main]]
	name       = "FAQ"
	url        = "/faq/"
	weight     = 2
	parent     = "menu.support"

[[menu.main]]
	name       = "SHOP"
	identifier = "menu.shop"
	url        = "https://nmimusic.booth.pm/"
	weight     = 6

[[menu.main]]
	name       = "LINKS"
	url        = "/links/"
	weight     = 7

[[menu.main]]
	name       = "CONTACT"
	url        = "/contact/"
	weight     = 8
	
[[menu.main]]
	name       = "POLICIES"
	url        = "/policies/"
	weight     = 9
